sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t skrmskdl2/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true skrmskdl2/docker-react-app npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-01"
  env: "Dockerreact01-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-250058502806
  bucket_path: "docker-react-01"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  
